language: python

python:
  - 2.7
  - 3.6

env:
- TOXENV=py27
- TOXENV=py36
- TOXENV=cov

branches:
  only:
    - master
    - develop

install: pip install --quiet tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet coveralls;
    coveralls;
  fi
